version: '3.0'
services:
  db:
    platform: linux/amd64
    image: mysql:5.7
    environment:
      TZ: "America/Sao_Paulo"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: project
      MYSQL_PORT: 3308
      MYSQL_HOST: 127.0.0.1
    ports:
      - "3308:3306"
